apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: otel-collector-daemonset
  namespace: ot-test
  labels:
    app: otel-collector
spec:
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      serviceAccountName: otel-collector
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector-contrib:latest
        command:
          - "/otelcol-contrib"  
          - "--config=/conf/otel-collector-config.yaml"
        volumeMounts:
          - name: config-volume
            mountPath: /conf
          - name: varlog
            mountPath: /var/log
      volumes:
        - name: config-volume
          configMap:
            name: otel-collector-config
        - name: varlog
          hostPath:
            path: /var/log
            type: Directory
